version: '3.3'

services:
  postgres_capital:
    container_name: postgres_capital    
    image: postgres
    env_file:
      - .env
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./postgres_data:/tmp/data
      - postgres_capital:/data/postgres
    ports:
      - ${POSTGRES_PORT}:5432
  
  pgadmin:
    container_name: pgadmin_container
    depends_on:
      - postgres_capital
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - ${PGADMIN_PORT}:80
  
  flyway:
    container_name: flyway_container
    image: flyway/flyway
    restart: on-failure:3
    command: info migrate
    volumes:
      - ../database/local:/tmp/database/local
      - ../database/server:/tmp/database/server
    env_file:
      - .env
    depends_on:
      - postgres_capital
      
volumes:
    postgres_capital:
